### ISSUE TITLE
Invalid language tag: pt_br

### ISSUE THREAD

**Issue by jeffersoncardoso** [aimeos/aimeos-laravel#286] opened 2019-08-11 18:12 UTC
1. Version 2018.10
2. Operating system Windows

When i change the language to pt_br on Administration panel, the dashboard not load and an error is shown on console window: Uncaught RangeError: Invalid language tag: pt_br (JQuery  error)

1. Go to Admin
2. Change language to pt_BR
3. Go to the dashboard

**Comment by aimeos** [comment] 2019-08-12 08:01
Thank you for your bug report. The problem is fixed in `aimeos/ai-admin-jqadm` `2018.10.x-dev`. Can you check if it works for you too?

**Closed** 2019-08-15 06:15 UTC
