### ISSUE TITLE
Admin access problem in CMS integration

### ISSUE THREAD

**Issue by kamranmalikte** [aimeos/aimeos-laravel#145] opened 2017-08-30 05:05 UTC
1- admin panel can't access if an admin buy anything.
2- a new admin can access admin panel for some time in testing front end its values changed

**Comment by aimeos** [comment] 2017-08-30 08:43
Can't reproduce this out of the box. Neither if the admin makes an order while logged in or not.
Please tell us the exact steps how to reproduce the problem.

**Comment by kamranmalikte** [comment] 2017-08-31 04:45
see this video and confirm that you understand the issue...
https://drive.google.com/file/d/0B8ko4xotk7c9T05odF80RW9kRWc/view?usp=sharing

**Comment by kamranmalikte** [comment] 2017-08-31 05:58
if something buying by an admin then admin cant access any admin functionalities and he access admin panel no more till he dont buy ..

**Comment by aimeos** [comment] 2017-08-31 09:48
First of all: Cool integration of the Aimeos backend into an CMS! :+1: 
Which CMS are you using and was it easy to integrate? Maybe you can share the integration or a documentation. Many developers are looking for something like this

**Comment by aimeos** [comment] 2017-08-31 09:55
In you screencast I see two problems and one is a guess:

1.) You want to add an article of a selection product that is out of stock. To fix that, set the stock level for that article to a value greater than 0

2.) There was a "non-recoverable error" in the address part of the checkout. You can find the error message and a stack trace in the madmin_log table

3.) I guess there's a problem at the end of the screencast that you want to change to the Aimeos admin interface but that doesn't work. Unfortunately, we can't do much here because we don't know your CMS integration. You can get closer to the issue with this steps:
- Look at the error log file of your web server
- Look into the madmin_log table if there are any errors
- Open the browser console and see if there are any Javascript errors

**Comment by kamranmalikte** [comment] 2017-09-07 07:41
no that is not error if stock is empty then it have to only show that stoock is empty and also we do not write another email in Adress bar we only can write the email who is authenticated and the problem is only that the when admin puchase something then admin panel cant access and the integration is another part i do not mix up the things integration is only by front end it do not affect anything.

**Comment by kamranmalikte** [comment] 2017-09-08 05:49
before the front end integration also i found this exception

**Comment by aimeos** [comment] 2017-09-09 16:49
Regarding the admin panel: Into which application did you integrate the Aimeos backend?

**Comment by kamranmalikte** [comment] 2017-09-18 05:10
gameworn application that is developing now and not complete yet some of issues i have this is the major issue i faced that an admin user who can access admin panel from this url [34.199.158.185/admin_shop](url) and the user interface through http://34.199.158.185/list this url so when an admin buy something from user interface then he can not access the admin url its redirect to home page as your understanding i can make a video again

**Comment by kamranmalikte** [comment] 2017-09-28 13:43
it is still do not fix the issue

**Comment by aimeos** [comment] 2017-09-28 13:45
Since we don't know your application, we can't do anything here

**Comment by kamranmalikte** [comment] 2017-09-28 13:53
ok i make a video then may be you understand

**Comment by colinbarstow** [comment] 2017-10-11 09:03
Experiencing the exact same issue out of the box with no changes to CMS. 
To break this right down:

Step 1 created an admin user with email address colinbarstow@gmail.com
Step 2 Logged in to admin area and had a look around
Step 3 Opened front end in a new tab
Step 4 Placed an order (even though item was out of stock)
Step 5 went back to admin tab and clicked on sidebar item --Orders, error returned.
Step 6 went back in browser and tried another sidebar item, same error.
Step 7 visited the home page and logged out
Step 8 logged back in with same account and constantly redirected to /home
Step 9 Cannot access admin now with this account.

**Comment by aimeos** [comment] 2017-10-11 10:43
Thank you very much, that was really helpful! The problem was that the user groups were lost when saving the customer billing address after the checkout address page. This and the problem of the "add to basket" button if articles of a selection product are out of stock has been fixed in the latest release.

Please run `composer update` to get the new version

**Comment by colinbarstow** [comment] 2017-10-11 10:50
Great news! I've just run the composer update, i'll give it a run now and see the changes. Thanks guys

**Comment by kamranmalikte** [comment] 2017-10-11 20:33
thanx you guys it might very helpful a big bug around me before huhh.....

**Closed** 2017-10-19 09:09 UTC
