### ISSUE TITLE
Called unknown method "getBirthday" on class "Aimeos\MShop\Customer\Item\Standard"

### ISSUE THREAD

**Issue by oulfr** [aimeos/aimeos-laravel#371] opened 2021-03-24 13:54 UTC
In customer tables, when i choose to display the column birthday i have this exception

**Comment by aimeos** [comment] 2021-03-24 17:33
Thanks for the hint. The problem is now fixed in `aimeos/ai-admin-jqadm:2020.10.x-dev`:
https://github.com/aimeos/ai-admin-jqadm/commit/d3b0421f8034be8baba9cd0a7d9b890b4095fa55

**Closed by aimeos** 2021-03-24 17:33 UTC
