### ISSUE TITLE
Problem saving more than one product image in new admin interface

### ISSUE THREAD

**Issue by kamranmalikte** [aimeos/aimeos-laravel#144] opened 2017-08-25 10:32 UTC
![screen shot 2017-08-25 at 3 30 36 pm](https://user-images.githubusercontent.com/27995556/29710649-a05b690a-89aa-11e7-9735-c64bc83f4790.png)
![screen shot 2017-08-25 at 3 29 30 pm](https://user-images.githubusercontent.com/27995556/29710656-a45ea40e-89aa-11e7-9432-7b70c4fbf36b.png)

**Comment by aimeos** [comment] 2017-08-25 10:35
Which Laravel and Aimeos version are you using?

**Comment by kamranmalikte** [comment] 2017-08-26 06:01
laravel 5.4

**Comment by kamranmalikte** [comment] 2017-08-26 06:17
and aimeos 2017.07

**Comment by kamranmalikte** [comment] 2017-08-26 06:20
when i click existing item from backend and changes something and added something new a new error according to documentation it update 
![screen shot 2017-08-26 at 11 19 34 am](https://user-images.githubusercontent.com/27995556/29739150-797daab8-8a50-11e7-89be-007acadc88fc.png)

**Comment by aimeoscom** [comment] 2017-08-26 09:42
What is the exact Aimeos version?

Can you reproduce the problem in our demo? If yes, please tell us the steps to get the error:
http://admin.demo.aimeos.org

**Comment by kamranmalikte** [comment] 2017-08-28 04:46
![screen shot 2017-08-28 at 9 46 04 am](https://user-images.githubusercontent.com/27995556/29759495-c0185f32-8bd5-11e7-9ea5-95c3cf2aa513.png)

**Comment by kamranmalikte** [comment] 2017-08-28 04:50
while adding the new products different errors show

**Comment by aimeos** [comment] 2017-08-28 05:11
What are the exact steps to get this error?
Adding a new product with an image worked for me in the admin demo.

**Comment by kamranmalikte** [comment] 2017-08-28 05:13
ok i make video for u

**Comment by kamranmalikte** [comment] 2017-08-28 05:14
![screen shot 2017-08-28 at 10 14 34 am](https://user-images.githubusercontent.com/27995556/29760001-b94d5f3c-8bd9-11e7-8818-a775785e7e77.png)

**Comment by kamranmalikte** [comment] 2017-08-28 05:19
also this error found when i refresh the page after 5 min of getting previous error

**Comment by kamranmalikte** [comment] 2017-08-28 05:24
https://drive.google.com/file/d/0B8ko4xotk7c9ZmVJM3FIREdfYU0/view

**Comment by kamranmalikte** [comment] 2017-08-28 05:24
check it

**Comment by kamranmalikte** [comment] 2017-08-28 05:30
different other errors  also shown

**Comment by kamranmalikte** [comment] 2017-08-28 05:40
when you get this error then refresh the page anothor error you found

**Comment by aimeos** [comment] 2017-08-28 09:35
Thank you for the screencast! We were able to reproduce the image upload error and are working on a fix for that issue. It does only happen when uploading several images at once.

Regarding your notice about the page refresh: This happens if you save a product and an error occurs and try to refresh the page by hitting the enter key in the address bar. The browser will then do a GET request for that page but only POST requests are allowed. GET requests doesn't contain the necessary data and are therefore denied by the Laravel routes.

**Comment by kamranmalikte** [comment] 2017-08-28 10:08
ok thanks for support one more issue here in backend many products added but in front end only 3 default products shown how can i modify or show the new products 
![Uploading Screen Shot 2017-08-28 at 3.05.02 PM.
![screen shot 2017-08-28 at 3 04 07 pm](https://user-images.githubusercontent.com/27995556/29769197-b5631df2-8c02-11e7-8537-9356bec01734.png)
png…]()

**Comment by aimeos** [comment] 2017-08-28 10:11
You need to add them to a category. Otherwise, they are not shown in the frontend

**Comment by kamranmalikte** [comment] 2017-08-28 10:12
ok i see

**Comment by kamranmalikte** [comment] 2017-08-28 10:13
there are no any category yet can i add manually or how ?

**Comment by kamranmalikte** [comment] 2017-08-28 10:40
when i type some category it remove automatically

**Comment by aimeos** [comment] 2017-08-28 10:52
In the product category panel you can either click on the arrow down button to get the list of available categories or you can start typing in the input field to filter for categories that start with the entered characters. In both cases, you need to select one of the categories from the list because we need the ID of the category and this isn't available if you only type the name of the category.

**Comment by kamranmalikte** [comment] 2017-08-28 10:53
ok thanks a lot

**Comment by aimeos** [comment] 2017-08-28 12:51
Image upload bug has been fixed in new ai-admin-jqadm package.
You can update your installation by executing `composer update`.
Can you confirm that it works for you now?

**Comment by kamranmalikte** [comment] 2017-08-31 07:11
no its

**Comment by kamranmalikte** [comment] 2017-08-31 07:11
no its not recover more than one image cant save

**Comment by aimeos** [comment] 2017-08-31 12:22
We've finally found the problem: If you select images in the file selection dialog one by one, the browser will only upload the last image. We can't get around that so the new version will remove previously selected imaged from the list if you use the file upload dialog again.

You can install the new version using `composer update`

**Closed** 2017-08-31 12:24 UTC
